# Quick Start Instructions:
#
# 1. Copy .env.example to .env and configure:
#    cp .env.example .env
#
# 2. Add your coldkey mnemonic to .env:
#    COLDKEY_MNEMONIC="your mnemonic here"
#
# 3. To run a miner:
#    docker-compose up
#    
# 4. To run a validator:
#    ROLE=validator docker-compose up
#
# Note: Make sure you have enough TAO for registration and have posted
# your verification tweet if running a miner.

version: '3.8'

services:
  masa-node:
    image: masaengineering/agent-arena-subnet:${TAG:-latest}
    env_file: .env
    environment:
      - ROLE=miner
      - WALLET_NAME=subnet_59
      - HOTKEY_NAME=miner_1
      - MINER_PORT=8242
    volumes:
      - ${WALLET_PATH:-~/.bittensor}:/root/.bittensor
      - ./.env:/app/.env
    ports:
      - "8242:8242"
    restart: unless-stopped
