# ./start.sh to start the neuron
# Runs as Validator or Miner Instance on
# Masa Protocol Data Network on Bittensor
# Mainnet:
# netuid:59
# Testnet:
# netuid:249

x-neuron-base: &neuron-base
  image: masaengineering/agent-arena:${TAG:-latest}
  environment: &env-base
    NETWORK: ${NETWORK:-test}
    COLDKEY_MNEMONIC: ${COLDKEY_MNEMONIC}
    # Set NETUID based on network type - 249 for testnet, 59 for mainnet
    NETUID: ${NETUID:-249}
  volumes:
    - neuron_data:/root/.bittensor
    - ./startup:/app/startup
    - ./masa:/app/masa
  networks:
    - masa_network

services:
  validator:
    <<: *neuron-base
    environment:
      <<: *env-base
      ROLE: validator
    ports:
      - target: 8092
        published: ${AXON_PORT:-8092}
        protocol: tcp
        mode: host
      - target: 8000
        published: ${METRICS_PORT:-8000}
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: ${VALIDATOR_COUNT:-0}

  miner:
    <<: *neuron-base
    environment:
      <<: *env-base
      ROLE: miner
    ports:
      - target: 8093
        published: ${AXON_PORT:-8093}
        protocol: tcp
        mode: host
      - target: 8001
        published: ${METRICS_PORT:-8001}
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: ${MINER_COUNT:-1}

volumes:
  neuron_data:

networks:
  masa_network:
    driver: overlay
