# ./start.sh to start the neuron
# Runs as Validator or Miner Instance on
# Masa Protocol Data Network on Bittensor
# Mainnet:
# netuid:59
# Testnet:
# netuid:249

x-neuron-base: &neuron-base
  image: masaengineering/agent-arena-subnet:${TAG:-latest}
  environment: &env-base
    SUBTENSOR_NETWORK: ${SUBTENSOR_NETWORK:-test}
    ROLE: validator
  volumes:
    - ./.bittensor:/root/.bittensor
    - ./startup:/app/startup
    - ./.env:/app/.env
  networks:
    - subnet

services:
  validator:
    <<: *neuron-base
    ports:
      - target: ${VALIDATOR_AXON_PORT:-8092}
        published: ${VALIDATOR_AXON_PORT:-8092}
        protocol: tcp
        mode: ingress
      - target: ${VALIDATOR_METRICS_PORT:-9000}
        published: ${VALIDATOR_METRICS_PORT:-9000}
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: ${VALIDATOR_COUNT:-0}

  miner:
    <<: *neuron-base
    environment:
      <<: *env-base
      ROLE: miner
    ports:
      - target: ${MINER_AXON_PORT:-8192}
        published: ${MINER_AXON_PORT:-8192}
        protocol: tcp
        mode: ingress
      - target: ${MINER_METRICS_PORT:-9100}
        published: ${MINER_METRICS_PORT:-9100}
        protocol: tcp
        mode: ingress
      - target: ${MINER_GRAFANA_PORT:-3000}
        published: ${MINER_GRAFANA_PORT:-3000}
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: ${MINER_COUNT:-0}
      restart_policy:
        condition: none

volumes:
  neuron_data:

networks:
  subnet:
    driver: overlay
