# Quick Start Instructions:
#
# 1. Run a miner:
#    docker compose up
#    
# 2. Run a validator:
#    ROLE=validator docker compose up
#
# Note: All configuration can be overridden via .env file
# See .env.example for available options
services:
  masa-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: masaengineering/agent-arena-subnet:${TAG:-latest}
    env_file: .env
    environment:
      - ROLE=${ROLE:-miner}
      - WALLET_NAME=${WALLET_NAME:-default}
      - HOTKEY_NAME=${HOTKEY_NAME:-default}
      - MINER_AXON_PORT=${MINER_AXON_PORT:-8903}
      - MINER_METRICS_PORT=${MINER_METRICS_PORT:-8000}
      - MINER_GRAFANA_PORT=${MINER_GRAFANA_PORT:-3000}
      - NETUID=${NETUID:-59}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-finney}
      - PYTHONUNBUFFERED=1
    volumes:
      - ${WALLET_PATH:-$HOME/.bittensor}:/root/.bittensor
      - .:/app  # Mount the entire codebase
      - ./.env:/app/.env
    ports:
      - "${MINER_AXON_PORT:-8903}:${MINER_AXON_PORT:-8903}"
    restart: unless-stopped
  
  miner:
    build:
      context: .
      dockerfile: Dockerfile
    image: masaengineering/agent-arena-subnet:${TAG:-latest}
    env_file: .env
    environment:
      - ROLE=miner
      - WALLET_NAME=${WALLET_NAME:-default}
      - HOTKEY_NAME=${HOTKEY_NAME:-default}
      - MINER_AXON_PORT=${MINER_AXON_PORT:-8903}
      - MINER_METRICS_PORT=${MINER_METRICS_PORT:-8000}
      - MINER_GRAFANA_PORT=${MINER_GRAFANA_PORT:-3000}
      - MIN_STAKE_THRESHOLD=${MIN_STAKE_THRESHOLD:-0}
      - ENV=${ENV:-prod}
      - NETUID=${NETUID:-59}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-finney}
      - PYTHONUNBUFFERED=1
    volumes:
      - ${WALLET_PATH:-$HOME/.bittensor}:/root/.bittensor
      - .:/app
      - ./.env:/app/.env
    ports:
      - "${MINER_AXON_PORT:-8903}:${MINER_AXON_PORT:-8903}"
    restart: unless-stopped

  validator:
    build:
      context: .
      dockerfile: Dockerfile
    image: masaengineering/agent-arena-subnet:${TAG:-latest}
    env_file: .env
    environment:
      - ROLE=validator
      - WALLET_NAME=${VALIDATOR_WALLET_NAME:-default}
      - HOTKEY_NAME=${VALIDATOR_HOTKEY_NAME:-default}
      - VALIDATOR_AXON_PORT=${VALIDATOR_AXON_PORT:-8142}
      - VALIDATOR_METRICS_PORT=${VALIDATOR_METRICS_PORT:-8001}
      - VALIDATOR_GRAFANA_PORT=${VALIDATOR_GRAFANA_PORT:-3001}
      - NETUID=${NETUID:-59}
      - ENV=${ENV:-prod}
      - SUBTENSOR_NETWORK=${SUBTENSOR_NETWORK:-finney}
      - PYTHONUNBUFFERED=1
    volumes:
      - ${WALLET_PATH:-$HOME/.bittensor}:/root/.bittensor
      - .:/app
      - ./.env:/app/.env
    ports:
      - "${VALIDATOR_AXON_PORT:-8142}:${VALIDATOR_AXON_PORT:-8142}"
    restart: unless-stopped
