# ./start.sh to start the neuron
# Runs as Validator or Miner Instance on
# Masa Protocol Data Network on Bittensor
# Mainnet:
# netuid:59
# Testnet:
# netuid:249

x-neuron-base: &neuron-base
  image: masaengineering/agent-arena-subnet:${TAG:-latest}
  environment:
    SUBTENSOR_NETWORK: ${SUBTENSOR_NETWORK:-test}
    PATH: /app/venv/bin:${PATH}
  volumes:
    - ./.bittensor:/root/.bittensor
    - ./startup:/app/startup
    - ./.env:/app/.env
  networks:
    - subnet

services:
  validator:
    <<: *neuron-base
    environment:
      ROLE: validator
      SUBTENSOR_NETWORK: ${SUBTENSOR_NETWORK:-test}
      PYTHONUNBUFFERED: 1
      LOGLEVEL: DEBUG
    command: make run-validator
    ports:
      - target: ${VALIDATOR_AXON_PORT}
        published: ${VALIDATOR_AXON_PORT}
        protocol: tcp
        mode: ingress
      - target: ${VALIDATOR_METRICS_PORT}
        published: ${VALIDATOR_METRICS_PORT}
      - target: ${VALIDATOR_GRAFANA_PORT}
        published: ${VALIDATOR_GRAFANA_PORT}
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: ${VALIDATOR_COUNT:-0}
      restart_policy:
        condition: any
        delay: 5s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  miner:
    <<: *neuron-base
    environment:
      ROLE: miner
      SUBTENSOR_NETWORK: ${SUBTENSOR_NETWORK:-test}
      PYTHONUNBUFFERED: 1
      LOGLEVEL: DEBUG
    command: python3 -m startup
    ports:
      - target: ${MINER_AXON_PORT}
        published: ${MINER_AXON_PORT}
        protocol: tcp
        mode: ingress
      - target: ${MINER_METRICS_PORT}
        published: ${MINER_METRICS_PORT}
        protocol: tcp
        mode: ingress
      - target: ${MINER_GRAFANA_PORT}
        published: ${MINER_GRAFANA_PORT}
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: ${MINER_COUNT}
      restart_policy:
        condition: any
        delay: 5s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  neuron_data:

networks:
  subnet:
    driver: overlay
