name: agent-arena-subnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - fastapi
  - uvicorn
  - pydantic
  - python-dotenv
  - requests
  - cryptography
  - pytest
  - pip
  - pip:
    - uvicorn==0.30.5
    - fastapi==0.112.0
    - pydantic==2.9.2
    - numpy==2.1.3
    - pandas==2.2.3
    - fiber @ git+https://github.com/rayonlabs/fiber.git@199d6432b748c2a93c3ee0c34db72418b19c6d7f
    - py-bip39-bindings==0.1.12
    - py-ed25519-zebra-bindings==1.1.0
    - py-sr25519-bindings==0.2.1
    - substrate-interface==1.7.10
    - scalecodec==1.2.11
    - tweepy==4.14.0 