name: 'Delete All Agent Arena Subnet Images from Docker Hub'

on:
  push:
    branches:
      - docker-compose-up

jobs:
  delete-images:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Delete repository and all images
        run: |
          curl -X DELETE \
            -H "Authorization: Bearer $(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${{ secrets.DOCKER_USERNAME }}'", "password": "'${{ secrets.DOCKER_PASSWORD }}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)" \
            https://hub.docker.com/v2/repositories/masaengineering/agent-arena/

      - name: Verify deletion
        run: |
          echo "🗑️ Attempted to delete all images from masaengineering/agent-arena-subnet"
          echo "Please verify in Docker Hub that the repository has been removed" 