# Docker Compose configuration for Agent Arena Subnet
# Runs Validator or Miner Instance on Bittensor
# Mainnet: netuid 59 (Agent Arena)
# Testnet: netuid 249 (Agent Arena Test)

x-neuron-base: &neuron-base
  image: masaengineering/agent-arena:${TAG:-latest}
  environment: &env-base
    NETWORK: ${NETWORK:-test}
    COLDKEY_MNEMONIC: ${COLDKEY_MNEMONIC}
    NETUID: ${NETUID:-249}  # Defaults to testnet, override with 59 for mainnet
  volumes:
    - neuron_data:/root/.bittensor
    - ./startup:/app/startup
    - ./neurons:/app/neurons  # Mount Agent Arena specific code
  networks:
    - agent_arena_network

services:
  validator:
    <<: *neuron-base
    environment:
      <<: *env-base
      ROLE: validator
    ports:
      - target: 8092
        published: ${AXON_PORT:-8092}
        protocol: tcp
        mode: host
      - target: 8000
        published: ${METRICS_PORT:-8000}
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: ${VALIDATOR_COUNT:-0}

  miner:
    <<: *neuron-base
    environment:
      <<: *env-base
      ROLE: miner
      X_API_KEY: ${X_API_KEY:-""}  # X API key for agent interactions
    ports:
      - target: 8093
        published: ${AXON_PORT:-8093}
        protocol: tcp
        mode: host
      - target: 8001
        published: ${METRICS_PORT:-8001}
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: ${MINER_COUNT:-1}

volumes:
  neuron_data:

networks:
  agent_arena_network:
    driver: overlay
